In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
raw_mail_data = pd.read_csv('/content/mail_data.csv')

In [3]:
raw_mail_data.shape

(5572, 2)

In [4]:
raw_mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
raw_mail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [6]:
raw_mail_data['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
mail_data = raw_mail_data.where((pd.notnull(raw_mail_data)), '')

In [8]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
mail_data.loc[mail_data['Category'] == 'spam', 'Category',] = 0
mail_data.loc[mail_data['Category'] == 'ham', 'Category',] = 1

In [10]:
X = mail_data['Message']
Y = mail_data['Category']

In [11]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [12]:
Y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1234)

In [14]:
feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [15]:
model = LogisticRegression()

In [16]:
model.fit(X_train_features, Y_train)

LogisticRegression()

In [17]:
print(X_train_features.shape)
print(Y_train.shape)

(4457, 7407)
(4457,)

In [18]:
prediction_on_training_data = model.predict(X_train_features)
Accuracy_Train = accuracy_score(Y_train, prediction_on_training_data)

prediction_on_test_data = model.predict(X_test_features)
Accuracy_Test = accuracy_score(Y_test, prediction_on_test_data)

In [19]:
print(Accuracy_Train)
print(Accuracy_Test)

0.969710567646399
0.9560538116591928

In [20]:
input_mail = ['Thanks for your subscription to Ringtone UK your mobile will be charged £5/month Please confirm by replying YES or NO. If you reply NO you will not be charged']

In [21]:
mail_data[25:35]

   Category                                            Message
25        1  Just forced myself to eat a slice. I'm really ...
26        1                     Lol your always so convincing.
27        1  Did you catch the bus ? Are you frying an egg ...
28        1  I'm back &amp; we're packing the car now, I'll...
29        1  Ahhh. Work. I vaguely remember that! What does...
30        1  Wait that's still not all that clear, were you...
31        1  Yeah he got in at 2 and was v apologetic. n ha...
32        1                      K tell me anything about you.
33        1  For fear of fainting with the of all that hous...
34        0  Thanks for your subscription to Ringtone UK yo...

In [22]:
mail_data['Message'][34]

'Thanks for your subscription to Ringtone UK your mobile will be charged £5/month Please confirm by replying YES or NO. If you reply NO you will not be charged'

In [23]:
input_mail = ['Thanks for your subscription to Ringtone UK your mobile will be charged £5/month Please confirm by replying YES or NO. If you reply NO you will not be charged']
input_data_features = feature_extraction.transform(input_mail)
prediction = model.predict(input_data_features)
print(prediction)

[0]

In [25]:
if prediction[0] == 1:
  print('ham')
else:
  print('spam')

spam

In [26]:
import pickle

In [29]:
with open('spam_mail.pickle', 'wb') as f:
  pickle.dump(model, f)